### PR TITLE
defer-length feature supported (issue #13)

### PR DESCRIPTION
**Pull request by rfelgent**
Hello @Acconut ,

this is my first version of the "upload-defer-length" feature of the TUS protocol spec. 
I implemented an "enableDefer" method for the defer-length feature like you did with the "enableResuming" method for resumable upload feature. 

This pull requests targets the issue #13

### CODE REVIEW

**Comment by Acconut** [comment]
Frankly, I am a bit lost with how this new API should be used. Could you please provide an example?

**Comment by rfelgent** [comment]
Hi @Acconut ,

sorry for my late response. I was on a vacation and now I am back.

Frankly, I am a bit lost, too :) A came across this feature when implementing my tus server side version. Therefore, I wanted to support this feature only and did not pay much attention _when_ and _how_ to use it. 

The only scenario I can think of is some kind of streaming business logic where you do not know the total size of the stream in advance.

**Comment by Acconut** [comment]
> The only scenario I can think of is some kind of streaming business logic where you do not know the total size of the stream in advance.

Exactly, there a few examples which come to my mind:
- Upload a service's logs while it's still running
- Upload a user's live video stream
- Upload a video while it's being transcoded (and its resulting size is unknown)

> What do you think? How should we continue with this MR ?

I am not sure either, to be honest. On one hand, I agree with you, that it would be amazing to have a client implementation which supported the full feature set. On the other hand, no official server implementation server (namely tusd and tus-node-server) supports this feature yet, making developing and testing it though. Furthermore, since we both don't have actual use case for it, we may not be in the best position to design an good API for this feature. Maybe it's a better step to wait until we have more insight into the use cases. What do you think about this?

**Comment by rfelgent** [comment]
Hello @Acconut, 

the more I talk about the "streaming" topic the more I realize that this features not a main focus of the TUS protocol. At the moment, there is no reference implementation supporting this feature.

Thus, let us drop this merge request.

**Comment by Acconut** [comment]
> Thus, let us drop this merge request.

Yes, I agree with you. Nevertheless, your efforts are greatly appreciated, thank you for that :)

**Pull request closed without merging**
